[build]
  # Directory to publish (current directory since it's a static site)
  publish = "."
  
  # Build command (not needed for static site, but can be used for preprocessing)
  # command = "echo 'Building thePlanner-1...'"

[build.environment]
  # Environment variables for build process
  NODE_VERSION = "18"

# Redirect rules for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}
  force = false

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://kit.fontawesome.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://ka-f.fontawesome.com; font-src 'self' https://fonts.gstatic.com https://ka-f.fontawesome.com; img-src 'self' data:; connect-src 'self' https://*.onrender.com https://api.openai.com https://api.perplexity.ai https://thetranscriber4theblanner.onrender.com https://ka-f.fontawesome.com;"

# Specific headers for API calls
[[headers]]
  for = "/config.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404